### ISSUE TITLE
Plugin not movable...

### ISSUE THREAD

**Issue by gr8distance** [addsict/gcp-console-colorize#5]
Thank you for making this wonderful Plugin!

Today, I got a normal looks header bars...(´・ω・`)
maybe, header bars css classes was changed...

Please fix it 🙏

**Comment by gr8distance** [comment]
Whoo!
Great PR is comming!

**Comment by yfuruyama** [comment]
@aimerald, @windyakin
Thanks for filing a issue and creating a PR!
I'll review it and publish to Chrome store later.
Once published, I'll notice you guys.

Thanks!

**Comment by yfuruyama** [comment]
@aimerald, @windyakin 
I just published gcp-console-colorize [v1.5](https://chrome.google.com/webstore/detail/higjahjicmccalicmgfpokdmooopdhej/publish-delayed?hl=ja) to Chrome Web Store.
Thank you for contributing this project!
