### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by whyman** [addsict/gcp-console-colorize#7]
Any chance of getting this for Firefox?

**Comment by yfuruyama** [comment]
Sorry there is no plan to create a Firefox extension.

Please feel free to fork this repository and create one for Firefox.

**Comment by madhukar93** [comment]
@jontutcher, any plans for publishing the Firefox version/making the repo available publicly?

**Comment by araigumaG** [comment]
I made fork [repo](https://github.com/araigumaG/gcp-console-colorize-firefox) for Firefox version including little difference.
There is also the signed (≒ready to use) add-on (`.xpi`) package.

@yfuruyama 
IMHO, all changes keep compatibility with Chrome version, so shall I make PR in this repo?

**Comment by yfuruyama** [comment]
@araigumaG Thank you for creating a Firefox extension. Actually I can't maintain the Firefox version, so please keep using your repository for Firefox.

I will mention and link your repository in README.
