### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by jontutcher** [addsict/gcp-console-colorize#8]
Hi there,

I've forked your repo in order to compile it for Firefox, as you mentioned in #7. I'd love to publish it back to Github and submit it to the Firefox extensions store with a credit to you - do you mind me doing so? If so, could you clarify licensing in this repo? I'd happily submit a PR to add an [MIT license](https://choosealicense.com/licenses/mit/) if you think it suits your project :) 

Thanks for your work anyhow!

**Comment by yfuruyama** [comment]
Hi Jon,

Thanks for creating an extension for Firefox! I don't mind if you submit the extension to the store.

I just added the [LICENSE file](https://github.com/yfuruyama/gcp-console-colorize/blob/master/LICENSE) (Apache License 2.0), so please use it.

**Comment by jontutcher** [comment]
Brill, will do! Missed this - thanks a lot for doing that :)

**Comment by madhukar93** [comment]
@jontutcher hi, any plans for publishing the Firefox version/making the repo available publicly?
